
# Press Alt + [ to duplicate the Front Left channel to both sides
alt+, af toggle "lavfi=[pan=stereo|c0=FL|c1=FL]"

# Press Alt + ] to duplicate the Front Right channel to both sides
alt+. af toggle "lavfi=[pan=stereo|c0=FR|c1=FR]"

